name: GenerateProtoWorkflow
on:
  repository_dispatch:
    types: [ProtoFileChanges]
jobs:
  protoGenJobs:
    runs-on: [ubuntu-latest]
    steps:
      - name: Changes Log
        run: |
          echo commit message: ${{ github.event.client_payload.message }}.
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
      - name: Set git global config
        run: |
          git config --global user.name "Tarsidi"
          git config --global user.email "tarsidi.danesh@tiket.com"
      - name: Genereate code for squzy-storage protofile
        uses: PxyUp/protoc-actions@v3.0.0
        with:
          path: -I./ --go_opt=paths=source_relative --go_opt=Mproto/hello-world.proto=github.com/tarsidi-danesh/grpc-intro-go --go_out=plugins=grpc:. proto/hello-world.proto
      - name: Commit & Push changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Tarsidi
          author_email: tarsidi.danesh@tiket.com
          message: 'generate proto'
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
